# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user',
            new_name='user_liked',
        ),
        migrations.AddField(
            model_name='friend',
            name='user_liked_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friended_by', to='main.User'),
            preserve_default=False,
        ),
    ]
