# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170302_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user_liked',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user_liked_by',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
